### ISSUE TITLE
Xcode Simulator not found when running ios from a new Ignite project

### ISSUE THREAD

**Issue by budda** [infinitered/ignite-andross#263]
---
What's going on?

A default macOS Simulator doesn't open when running ios project if the project is created with Ignite CLI.

If i generate the same base project with react-native then it does open the default iPhone X simulator.

---
Steps to reproduce

I created a project with
```react-native init awesome```
and then ran it with
```react-native run-ios```
and the Simulator opened and showed the app.

I created a project with
```ignite n awesomeIgnite```
and then ran it with
```react-native run-ios```
and no Simulator opens. An error instead:
```Found Xcode project awesomeIgnite.xcodeproj

Could not find iPhone X simulator

Error: Could not find iPhone X simulator
    at resolve (/Users/mikec/Documents/code/mobile/awesomeIgnite/node_modules/react-native/local-cli/runIOS/runIOS.js:149:13)
    at new Promise (<anonymous>)
    at runOnSimulator (/Users/mikec/Documents/code/mobile/awesomeIgnite/node_modules/react-native/local-cli/runIOS/runIOS.js:134:10)
    at Object.runIOS [as func] (/Users/mikec/Documents/code/mobile/awesomeIgnite/node_modules/react-native/local-cli/runIOS/runIOS.js:106:12)
    at Promise.resolve.then (/Users/mikec/Documents/code/mobile/awesomeIgnite/node_modules/react-native/local-cli/cliEntry.js:117:22)
```

---
`ignite doctor` results:

```
System
  platform           darwin
  arch               x64
  cpu                8 cores                                           Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  directory          /Users/mikec/Documents/code/mobile/MyAppAndross

JavaScript
  node               11.13.0         /usr/local/bin/node
  npm                6.7.0           /usr/local/bin/npm
  yarn               not installed

React Native
  react-native-cli   2.0.1
  app rn version     0.57.7

Ignite
  ignite             2.2.4            /usr/local/bin/ignite
  boilerplate        ignite-andross

Android
  java               1.8.0_181    /usr/bin/java
  android home       -            undefined

iOS
  xcode              10.2
```

**Comment by budda** [comment]
This has been fixed for Bowser boilerplate, see https://github.com/infinitered/ignite/issues/1401#issuecomment-481777589

**Comment by jamonholmgren** [comment]
@budda We need to upgrade Andross to 0.59.0. In Bowser it was a simple version number bump. Want to tackle upgrading it?

**Comment by budda** [comment]
> @budda We need to upgrade Andross to 0.59.0. In Bowser it was a simple version number bump. Want to tackle upgrading it?

I dropped a pull request in a couple of days ago to do the RN update to 0.59.3 at https://github.com/infinitered/ignite-andross/pull/264

There's more work to be done to fix it though I think. I'm travelling at the moment so don't have long chunks of time to donate.

**Comment by budda** [comment]
Okay, tried to run-ios after upgrading react-native AND react peer dependency.

xcode chokes with the following:

```
info Found Xcode project igniteAndross.xcodeproj
info Building using "xcodebuild -project igniteAndross.xcodeproj -configuration Debug -scheme igniteAndross -destination id=A067EA43-4AB2-43C5-BAE2-01892A954AF5 -derivedDataPath build/igniteAndross"
info User defaults from command line:
    IDEDerivedDataPathOverride = /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross

Build settings from command line:

info     TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault


info note: Using new build system

info note: Planning build

info note: Using build description from disk

info Build system information

info warning: The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.2.99. (in target 'RNGestureHandler')

info 

info PhaseScriptExecution Start\ Packager /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/React.build/Script-006B79A01A781F38006873D1.sh (in target: React)
    cd /Users/mikec/Documents/code/mobile/igniteAndross/node_modules/react-native/React
    /bin/sh -c /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/React.build/Script-006B79A01A781F38006873D1.sh

info Connection to localhost port 8081 [tcp/sunproxyadmin] succeeded!

info 

info PhaseScriptExecution Include\ RCTJSCProfiler /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/React.build/Script-142C4F7F1B582EA6001F0B58.sh (in target: React)
    cd /Users/mikec/Documents/code/mobile/igniteAndross/node_modules/react-native/React
    /bin/sh -c /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/React.build/Script-142C4F7F1B582EA6001F0B58.sh

info 

info Ld /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Products/Debug-iphonesimulator/igniteAndross.app/igniteAndross normal x86_64 (in target: igniteAndross)
    cd /Users/mikec/Documents/code/mobile/igniteAndross/ios
    export IPHONEOS_DEPLOYMENT_TARGET=9.0
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk -L/Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Products/Debug-iphonesimulator -F/Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Products/Debug-iphonesimulator -filelist /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Intermediates.noindex/igniteAndross.build/Debug-iphonesimulator/igniteAndross.build/Objects-normal/x86_64/igniteAndross.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=9.0 -Xlinker -object_path_lto -Xlinker /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Intermediates.noindex/igniteAndross.build/Debug-iphonesimulator/igniteAndross.build/Objects-normal/x86_64/igniteAndross_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -ObjC -lc++ -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Intermediates.noindex/igniteAndross.build/Debug-iphonesimulator/igniteAndross.build/igniteAndross.app-Simulated.xcent /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Products/Debug-iphonesimulator/libRCTBlob.a /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Products/Debug-iphonesimulator/libRCTAnimation.a /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Products/Debug-iphonesimulator/libReact.a /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Products/Debug-iphonesimulator/libRCTActionSheet.a /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Products/Debug-iphonesimulator/libRCTGeolocation.a /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Products/Debug-iphonesimulator/libRCTImage.a /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Products/Debug-iphonesimulator/libRCTLinking.a /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Products/Debug-iphonesimulator/libRCTNetwork.a /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Products/Debug-iphonesimulator/libRCTSettings.a /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Products/Debug-iphonesimulator/libRCTText.a /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Products/Debug-iphonesimulator/libRCTVibration.a /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Products/Debug-iphonesimulator/libRCTWebSocket.a -lRNGestureHandler -lRNVectorIcons -lRNDeviceInfo -Xlinker -dependency_info -Xlinker /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Intermediates.noindex/igniteAndross.build/Debug-iphonesimulator/igniteAndross.build/Objects-normal/x86_64/igniteAndross_dependency_info.dat -o /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Products/Debug-iphonesimulator/igniteAndross.app/igniteAndross

info Undefined symbols for architecture x86_64:
  "_JSClassCreate", referenced from:

info       facebook::jsc::JSCRuntime::createObject(std::__1::shared_ptr<facebook::jsi::HostObject>)::$_0::operator()() const in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>)::$_1::operator()() const in libReact.a(JSCRuntime.o)

info   "_JSContextGetGlobalObject", referenced from:

info       facebook::jsc::JSCRuntime::global() in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>)::HostFunctionMetadata::initialize(OpaqueJSContext const*, OpaqueJSValue*) in libReact.a(JSCRuntime.o)

info   "_JSEvaluateScript", referenced from:

info       facebook::jsc::JSCRuntime::evaluateJavaScript(std::__1::unique_ptr<facebook::jsi::Buffer const, std::__1::default_delete<facebook::jsi::Buffer const> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libReact.a(JSCRuntime.o)

info   "_JSGlobalContextCreateInGroup", referenced from:

info       facebook::jsc::JSCRuntime::JSCRuntime() in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::JSCRuntime() in libReact.a(JSCRuntime.o)

info   "_JSGlobalContextRelease", referenced from:

info       facebook::jsc::JSCRuntime::JSCRuntime() in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::~JSCRuntime() in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::JSCRuntime() in libReact.a(JSCRuntime.o)

info   "_JSGlobalContextRetain", referenced from:

info       facebook::jsc::JSCRuntime::JSCRuntime(OpaqueJSContext*) in libReact.a(JSCRuntime.o)

info   "_JSObjectCallAsConstructor", referenced from:

info       facebook::jsc::JSCRuntime::callAsConstructor(facebook::jsi::Function const&, facebook::jsi::Value const*, unsigned long) in libReact.a(JSCRuntime.o)

info   "_JSObjectCallAsFunction", referenced from:

info       facebook::jsc::JSCRuntime::call(facebook::jsi::Function const&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) in libReact.a(JSCRuntime.o)

info   "_JSObjectCopyPropertyNames", referenced from:

info       facebook::jsc::JSCRuntime::getPropertyNames(facebook::jsi::Object const&) in libReact.a(JSCRuntime.o)

info   "_JSObjectGetPrivate", referenced from:

info       facebook::jsc::JSCRuntime::getHostObject(facebook::jsi::Object const&) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::getHostFunction(facebook::jsi::Function const&) in libReact.a(JSCRuntime.o)

info       facebook::jsc::JSCRuntime::createObject(std::__1::shared_ptr<facebook::jsi::HostObject>)::HostObjectProxy::finalize(OpaqueJSValue*) in libReact.a(JSCRuntime.o)

info       facebook::jsc::JSCRuntime::createObject(std::__1::shared_ptr<facebook::jsi::HostObject>)::HostObjectProxy::getProperty(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSString*, OpaqueJSValue const**) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createObject(std::__1::shared_ptr<facebook::jsi::HostObject>)::HostObjectProxy::setProperty(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSString*, OpaqueJSValue const*, OpaqueJSValue const**) in libReact.a(JSCRuntime.o)

info       facebook::jsc::JSCRuntime::createObject(std::__1::shared_ptr<facebook::jsi::HostObject>)::HostObjectProxy::getPropertyNames(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSPropertyNameAccumulator*) in libReact.a(JSCRuntime.o)

info       facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>)::HostFunctionMetadata::initialize(OpaqueJSContext const*, OpaqueJSValue*) in libReact.a(JSCRuntime.o)

info       ...

info   "_JSObjectGetProperty", referenced from:

info       facebook::jsc::JSCRuntime::getProperty(facebook::jsi::Object const&, facebook::jsi::String const&) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::getProperty(facebook::jsi::Object const&, facebook::jsi::PropNameID const&) in libReact.a(JSCRuntime.o)

info       facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>)::HostFunctionMetadata::initialize(OpaqueJSContext const*, OpaqueJSValue*) in libReact.a(JSCRuntime.o)

info   "_JSObjectGetPropertyAtIndex", referenced from:

info       facebook::jsc::JSCRuntime::getValueAtIndex(facebook::jsi::Array const&, unsigned long) in libReact.a(JSCRuntime.o)

info   "_JSObjectGetPrototype", referenced from:

info       facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>)::HostFunctionMetadata::initialize(OpaqueJSContext const*, OpaqueJSValue*) in libReact.a(JSCRuntime.o)

info   "_JSObjectHasProperty", referenced from:

info       facebook::jsc::JSCRuntime::hasProperty(facebook::jsi::Object const&, facebook::jsi::String const&) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::hasProperty(facebook::jsi::Object const&, facebook::jsi::PropNameID const&) in libReact.a(JSCRuntime.o)

info   "_JSObjectIsFunction", referenced from:

info       facebook::jsc::JSCRuntime::isFunction(facebook::jsi::Object const&) const in libReact.a(JSCRuntime.o)

info   "_JSObjectMake", referenced from:

info       facebook::jsc::JSCRuntime::makeObjectValue(OpaqueJSValue*) const in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createObject(std::__1::shared_ptr<facebook::jsi::HostObject>) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>) in libReact.a(JSCRuntime.o)

info   "_JSObjectMakeArray", referenced from:

info       facebook::jsc::JSCRuntime::createArray(unsigned long) in libReact.a(JSCRuntime.o)

info   "_JSObjectSetPrivate", referenced from:

info       facebook::jsc::JSCRuntime::createObject(std::__1::shared_ptr<facebook::jsi::HostObject>)::HostObjectProxy::finalize(OpaqueJSValue*) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>)::HostFunctionMetadata::finalize(OpaqueJSValue*) in libReact.a(JSCRuntime.o)

info   "_JSObjectSetProperty", referenced from:

info       facebook::jsc::JSCRuntime::setPropertyValue(facebook::jsi::Object&, facebook::jsi::PropNameID const&, facebook::jsi::Value const&) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::setPropertyValue(facebook::jsi::Object&, facebook::jsi::String const&, facebook::jsi::Value const&) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createArray(unsigned long) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>)::HostFunctionMetadata::initialize(OpaqueJSContext const*, OpaqueJSValue*) in libReact.a(JSCRuntime.o)

info   "_JSObjectSetPropertyAtIndex", referenced from:

info       facebook::jsc::JSCRuntime::setValueAtIndexImpl(facebook::jsi::Array&, unsigned long, facebook::jsi::Value const&) in libReact.a(JSCRuntime.o)

info   "_JSObjectSetPrototype", referenced from:

info       facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>)::HostFunctionMetadata::initialize(OpaqueJSContext const*, OpaqueJSValue*) in libReact.a(JSCRuntime.o)

info   "_JSPropertyNameAccumulatorAddName", referenced from:

info       facebook::jsc::JSCRuntime::createObject(std::__1::shared_ptr<facebook::jsi::HostObject>)::HostObjectProxy::getPropertyNames(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSPropertyNameAccumulator*) in libReact.a(JSCRuntime.o)

info   "_JSPropertyNameArrayGetCount", referenced from:

info       facebook::jsc::JSCRuntime::getPropertyNames(facebook::jsi::Object const&) in libReact.a(JSCRuntime.o)

info   "_JSPropertyNameArrayGetNameAtIndex", referenced from:

info       facebook::jsc::JSCRuntime::getPropertyNames(facebook::jsi::Object const&) in libReact.a(JSCRuntime.o)

info   "_JSPropertyNameArrayRelease", referenced from:

info       facebook::jsc::JSCRuntime::getPropertyNames(facebook::jsi::Object const&) in libReact.a(JSCRuntime.o)

info   "_JSStringCreateWithUTF8CString", referenced from:

info       facebook::jsc::JSCRuntime::evaluateJavaScript(std::__1::unique_ptr<facebook::jsi::Buffer const, std::__1::default_delete<facebook::jsi::Buffer const> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createPropNameIDFromAscii(char const*, unsigned long) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createPropNameIDFromUtf8(unsigned char const*, unsigned long) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createStringFromUtf8(unsigned char const*, unsigned long) in libReact.a(JSCRuntime.o)
      facebook::jsc::(anonymous namespace)::getLengthString() in libReact.a(JSCRuntime.o)
      facebook::jsc::(anonymous namespace)::getEmptyString() in libReact.a(JSCRuntime.o)
      facebook::jsc::(anonymous namespace)::getNameString() in libReact.a(JSCRuntime.o)
      ...

info   "_JSStringGetMaximumUTF8CStringSize", referenced from:

info       facebook::jsc::(anonymous namespace)::JSStringToSTLString(OpaqueJSString*) in libReact.a(JSCRuntime.o)

info   "_JSStringGetUTF8CString", referenced from:

info       facebook::jsc::(anonymous namespace)::JSStringToSTLString(OpaqueJSString*) in libReact.a(JSCRuntime.o)

info   "_JSStringIsEqual", referenced from:

info       facebook::jsc::JSCRuntime::compare(facebook::jsi::PropNameID const&, facebook::jsi::PropNameID const&) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::strictEquals(facebook::jsi::String const&, facebook::jsi::String const&) const in libReact.a(JSCRuntime.o)

info   "_JSStringRelease", referenced from:

info       facebook::jsc::JSCRuntime::evaluateJavaScript(std::__1::unique_ptr<facebook::jsi::Buffer const, std::__1::default_delete<facebook::jsi::Buffer const> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::JSCStringValue::invalidate() in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createPropNameIDFromAscii(char const*, unsigned long) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createPropNameIDFromUtf8(unsigned char const*, unsigned long) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createValue(OpaqueJSValue const*) const in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>)::HostFunctionMetadata::initialize(OpaqueJSContext const*, OpaqueJSValue*) in libReact.a(JSCRuntime.o)

info   "_JSStringRetain", referenced from:

info       facebook::jsc::JSCRuntime::JSCStringValue::JSCStringValue(OpaqueJSString*, std::__1::atomic<long>&) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>)::HostFunctionMetadata::HostFunctionMetadata(facebook::jsc::JSCRuntime*, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>, unsigned int, OpaqueJSString*) in libReact.a(JSCRuntime.o)

info   "_JSValueIsArray", referenced from:

info       facebook::jsc::JSCRuntime::isArray(facebook::jsi::Object const&) const in libReact.a(JSCRuntime.o)

info   "_JSValueIsBoolean", referenced from:

info       facebook::jsc::JSCRuntime::createValue(OpaqueJSValue const*) const in libReact.a(JSCRuntime.o)

info   "_JSValueIsInstanceOfConstructor", referenced from:

info       facebook::jsc::JSCRuntime::instanceOf(facebook::jsi::Object const&, facebook::jsi::Function const&) in libReact.a(JSCRuntime.o)

info   "_JSValueIsNull", referenced from:

info       facebook::jsc::JSCRuntime::createValue(OpaqueJSValue const*) const in libReact.a(JSCRuntime.o)

info   "_JSValueIsNumber", referenced from:

info       facebook::jsc::JSCRuntime::createValue(OpaqueJSValue const*) const in libReact.a(JSCRuntime.o)

info   "_JSValueIsObject", referenced from:

info       facebook::jsc::JSCRuntime::createValue(OpaqueJSValue const*) const in libReact.a(JSCRuntime.o)

info   "_JSValueIsObjectOfClass", referenced from:

info       facebook::jsc::JSCRuntime::isHostObject(facebook::jsi::Object const&) const in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::isHostFunction(facebook::jsi::Function const&) const in libReact.a(JSCRuntime.o)

info   "_JSValueIsString", referenced from:

info       facebook::jsc::JSCRuntime::createValue(OpaqueJSValue const*) const in libReact.a(JSCRuntime.o)

info   "_JSValueIsUndefined", referenced from:

info       facebook::jsc::JSCRuntime::createValue(OpaqueJSValue const*) const in libReact.a(JSCRuntime.o)

info   "_JSValueMakeBoolean", referenced from:

info       facebook::jsc::JSCRuntime::valueRef(facebook::jsi::Value const&) in libReact.a(JSCRuntime.o)

info   "_JSValueMakeNull", referenced from:

info       facebook::jsc::JSCRuntime::valueRef(facebook::jsi::Value const&) in libReact.a(JSCRuntime.o)

info   "_JSValueMakeNumber", referenced from:

info       facebook::jsc::JSCRuntime::valueRef(facebook::jsi::Value const&) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createArray(unsigned long) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>)::HostFunctionMetadata::initialize(OpaqueJSContext const*, OpaqueJSValue*) in libReact.a(JSCRuntime.o)

info   "_JSValueMakeString", referenced from:

info       facebook::jsc::JSCRuntime::valueRef(facebook::jsi::Value const&) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>)::HostFunctionMetadata::initialize(OpaqueJSContext const*, OpaqueJSValue*) in libReact.a(JSCRuntime.o)

info   "_JSValueMakeUndefined", referenced from:

info       facebook::jsc::JSCRuntime::valueRef(facebook::jsi::Value const&) in libReact.a(JSCRuntime.o)

info       facebook::jsc::JSCRuntime::createObject(std::__1::shared_ptr<facebook::jsi::HostObject>)::HostObjectProxy::getProperty(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSString*, OpaqueJSValue const**) in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>)::HostFunctionMetadata::call(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSValue*, unsigned long, OpaqueJSValue const* const*, OpaqueJSValue const**) in libReact.a(JSCRuntime.o)

info   "_JSValueProtect", referenced from:

info       facebook::jsc::JSCRuntime::JSCObjectValue::JSCObjectValue(OpaqueJSContext*, std::__1::atomic<bool> const&, OpaqueJSValue*, std::__1::atomic<long>&) in libReact.a(JSCRuntime.o)

info   "_JSValueToBoolean", referenced from:

info       facebook::jsc::JSCRuntime::createValue(OpaqueJSValue const*) const in libReact.a(JSCRuntime.o)

info   "_JSValueToNumber", referenced from:

info       facebook::jsc::JSCRuntime::createValue(OpaqueJSValue const*) const in libReact.a(JSCRuntime.o)

info   "_JSValueToObject", referenced from:

info       facebook::jsc::JSCRuntime::createValue(OpaqueJSValue const*) const in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>)::HostFunctionMetadata::initialize(OpaqueJSContext const*, OpaqueJSValue*) in libReact.a(JSCRuntime.o)

info   "_JSValueToStringCopy", referenced from:

info       facebook::jsc::JSCRuntime::createValue(OpaqueJSValue const*) const in libReact.a(JSCRuntime.o)

info   "_JSValueUnprotect", referenced from:

info       facebook::jsc::JSCRuntime::JSCObjectValue::invalidate() in libReact.a(JSCRuntime.o)

info   "_kJSClassDefinitionEmpty", referenced from:

info       facebook::jsc::JSCRuntime::createObject(std::__1::shared_ptr<facebook::jsi::HostObject>)::$_0::operator()() const in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>)::$_1::operator()() const in libReact.a(JSCRuntime.o)

info ld: symbol(s) not found for architecture x86_64

info clang: error: linker command failed with exit code 1 (use -v to see invocation)

info 

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening igniteAndross.xcodeproj

** BUILD FAILED **


The following build commands failed:
	Ld /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Products/Debug-iphonesimulator/igniteAndross.app/igniteAndross normal x86_64
(1 failure)

debug Error: Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening igniteAndross.xcodeproj

** BUILD FAILED **


The following build commands failed:
	Ld /Users/mikec/Documents/code/mobile/igniteAndross/ios/build/igniteAndross/Build/Products/Debug-iphonesimulator/igniteAndross.app/igniteAndross normal x86_64
(1 failure)

    at ChildProcess.buildProcess.on.code (/Users/mikec/Documents/code/mobile/igniteAndross/node_modules/@react-native-community/cli/build/commands/runIOS/runIOS.js:231:16)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:1001:16)
    at Socket.stream.socket.on (internal/child_process.js:405:11)
    at Socket.emit (events.js:193:13)
    at Pipe._handle.close (net.js:614:12)
```
Which is the same as reported in https://github.com/infinitered/ignite/issues/1401#issuecomment-480997544 for the Bowser boilerplate.

**Comment by budda** [comment]
Hmm, fixed all the errors by doing ```rm -rf node_modules && npm install``` in the project folder.
Why I needed to do that just after creating a new project i'm not clear on.

**Comment by budda** [comment]
Something like running `react-native run-ios` 2-3 times the app eventually builds (!) and loads on the iOS Simulator.

I'm then greeted with a red banner error in the app:
```
null is not an object (evaluating 'RNDeviceInfo.systemManufacturer')

getManufacturer
    index.bundle?platform=ios&dev=true&minify=false:144008:26
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:143705:57
loadModuleImplementation
    index.bundle?platform=ios&dev=true&minify=false:276:14
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:139417:61
loadModuleImplementation
    index.bundle?platform=ios&dev=true&minify=false:276:14
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:132268:63
loadModuleImplementation
    index.bundle?platform=ios&dev=true&minify=false:276:14
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:132138:61
loadModuleImplementation
    index.bundle?platform=ios&dev=true&minify=false:276:14
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:132092:57
loadModuleImplementation
    index.bundle?platform=ios&dev=true&minify=false:276:14
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:112654:58
loadModuleImplementation
    index.bundle?platform=ios&dev=true&minify=false:276:14
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:112539:60
loadModuleImplementation
    index.bundle?platform=ios&dev=true&minify=false:276:14
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:109880:58
loadModuleImplementation
    index.bundle?platform=ios&dev=true&minify=false:276:14
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:1385:48
loadModuleImplementation
    index.bundle?platform=ios&dev=true&minify=false:276:14
guardedLoadModule
    index.bundle?platform=ios&dev=true&minify=false:152:47
global code
    index.bundle?platform=ios&dev=true&minify=false:154667:4
```

I then tried a `react-native link` followed by `react-native run-ios` and the app loads and displays the example screens fine! (grrr...)

Not the smoothest of setups.

**Comment by jamonholmgren** [comment]
Wow, yeah, that does seem rough. Thanks for the hard work @budda! I may tackle it tomorrow, not sure.
