### ISSUE TITLE
Create new app

### ISSUE THREAD

**Issue by JuanSeBestia** [infinitered/ignite-andross#266]
I get started with ignite, i can't create base proyect

``` bash
▶ ignite new igniteAndross  --boilerplate andross  
-----------------------------------------------
  (                  )   (                   
  )\ )   (        ( /(   )\ )    *   )       
 (()/(   )\ )     )\()) (()/(  ` )  /(   (   
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\  
 (_))    /(_))_   _((_) (_))   (_(_())  ((_) 
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _| 
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

🐉 You're using a prerelease version of Ignite CLI (ignite --version). Please report bugs!
   While it should be reasonably stable, we'd love more testing.
   Thank you for being a prerelease tester and please report bugs!
   https://github.com/infinitered/ignite/issues


🔥 igniting app igniteAndross
✔ using the Infinite Red boilerplate v2 (code name 'Andross')
✔ added React Native 0.59.3 in 39.29s
✔ Would you like Ignite Development Screens? · Yes
✔ What vector icon library will you use? · react-native-vector-icons
✔ What internationalization library will you use? · react-native-i18n
✔ What animation library will you use? · react-native-animatable
✔ Would you like to include redux-persist? · Yes
✔ added ignite-andross in 52.06s
an error occured while installing ignite-andross boilerplate.
TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.install (/home/juan/gits/igniteAndross/node_modules/ignite-andross/boilerplate.js:182:79)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error installing boilerplate

▶ node -v
v10.15.3

▶ ignite -v                                      
3.0.0-beta.3

```

**Comment by ryanlntn** [comment]
This is fixed with the release of Ignite 3 and the latest boilerplates.
