### ISSUE TITLE
[Bug] Can not Create new Project on Windows 10

### ISSUE THREAD

**Issue by conradkirschner** [infinitered/ignite-andross#299]
### Can not create new Project
---
What's going on?
I've installed ignite globally on Windows 10. 
Then I tried to use the wizzard to create a new project

---
- adding ignite-andross
- installing boilerplate
- using the Infinite Red boilerplate v2 (code name 'Andross')
√ using the Infinite Red boilerplate v2 (code name 'Andross')
- adding React Native 0.59.9 (30 seconds-ish)
√ added React Native 0.59.9 in 34.66s
an error occured while installing ignite-andross boilerplate.
Error: ENOENT: no such file or directory, chdir 'C:\Users\conrad\Desktop\programming project\react-native\ignite\NewsApi' -> 'NewsApi'
    at process.chdir (internal/process/main_thread_only.js:29:13)
    at Object.<anonymous> (C:\Users\conrad\AppData\Roaming\npm\node_modules\ignite-cli\build\extensions\reactNative.js:114:33)
    at step (C:\Users\conrad\AppData\Roaming\npm\node_modules\ignite-cli\build\extensions\reactNative.js:32:23)
    at Object.next (C:\Users\conrad\AppData\Roaming\npm\node_modules\ignite-cli\build\extensions\reactNative.js:13:53)
    at fulfilled (C:\Users\conrad\AppData\Roaming\npm\node_modules\ignite-cli\build\extensions\reactNative.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'chdir',
  path: 'C:\\Users\\conrad\\Desktop\\programming project\\react-native\\ignite\\NewsApi',
  dest: 'NewsApi'
}
error installing boilerplate

Doctor output
System
  platform           win32
  arch               x64
  cpu                8 cores      Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  directory          ignite       C:\Users\conrad\Desktop\programming project\react-native\ignite

JavaScript
  node               12.13.0      C:\Program Files\nodejs\node.EXE
  npm                6.12.0       C:\Program Files\nodejs\npm.CMD
  yarn               1.19.1       C:\Users\conrad\AppData\Roaming\npm\yarn.CMD

Ignite
  ignite-cli         3.3.1        C:\Users\conrad\AppData\Roaming\npm\ignite.CMD
  ignite src         build        C:\Users\conrad\AppData\Roaming\npm\node_modules\ignite-cli\build
  generators         {}

Android
  java               -            C:\Program Files\Java\jdk-12.0.1\bin\java.EXE
  android home       -            C:\Users\conrad\AppData\Local\Android\Sdk

**Comment by SPopenko** [comment]
@conradkirschner could you please share your workaround here?

**Comment by conradkirschner** [comment]
> @conradkirschner could you please share your workaround here?

Reinstalled windows then it worked, nevertheless such a unstable boilerplate is nothing that I want to use
